<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.10" />
	  <PackageReference Include="NAudio" Version="2.2.1" />
	  <PackageReference Include="NAudio.Asio" Version="2.2.1" />
	  <PackageReference Include="NAudio.Core" Version="2.2.1" />
	  <PackageReference Include="NAudio.Midi" Version="2.2.1" />
	  <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
	  <PackageReference Include="NAudio.WinForms" Version="2.2.1" />
	  <PackageReference Include="NAudio.WinMM" Version="2.2.1" />
	  <PackageReference Include="PDFtoImage" Version="5.1.1" />
	  <PackageReference Include="ZXing.Net" Version="0.16.10" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.13" />
	  <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
	  <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
	  <!--<PackageReference Include="Sdcb.PaddleInference" Version="3.0.1" />
	  <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.1.0.54" />
	  <PackageReference Include="Sdcb.PaddleOCR" Version="3.0.1" />
	  <PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="3.0.1" />-->
  </ItemGroup>

</Project>
