<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Resources\icon_128x128.ico</ApplicationIcon>
		<Version>4.1</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
		<Platforms>AnyCPU</Platforms>
	</PropertyGroup>

	<!--<ItemGroup>
		<RuntimeHostConfigurationOption Include="Switch.System.Windows.Appearance.DisableFluentThemeWindowBackdrop" Value="True" />
	</ItemGroup>-->


	<ItemGroup>
	  <None Remove="Resources\IconExit.png" />
	  <None Remove="Resources\IconHide.png" />
	  <None Remove="Resources\IconShow.png" />
	  <None Remove="Resources\KeyTest.jpg" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Resources\IconExit.png" />
	  <Resource Include="Resources\IconHide.png" />
	  <Resource Include="Resources\IconShow.png" />
	  <Resource Include="Resources\icon_128x128.ico" />
	  <Resource Include="Resources\KeyTest.jpg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="H.NotifyIcon.Wpf" Version="2.3.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="Notification.Wpf" Version="8.0.0" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
		<PackageReference Include="System.Speech" Version="9.0.10" />
		<PackageReference Include="TencentCloudSDK" Version="3.0.1336" />
		<PackageReference Include="WPFDevelopers" Version="0.0.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\鹰眼OCR_WPF\Screenshot_WPF\Screenshot_WPF.csproj" />
	</ItemGroup>

</Project>
