//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 鹰眼OCR_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("鹰眼OCR_WPF.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别后添加到末尾 的本地化字符串。
        /// </summary>
        public static string AddToEndAfterOCR {
            get {
                return ResourceManager.GetString("AddToEndAfterOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鹰眼OCR 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动下载表格 的本地化字符串。
        /// </summary>
        public static string AutoDownloadTable {
            get {
                return ResourceManager.GetString("AutoDownloadTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行卡 的本地化字符串。
        /// </summary>
        public static string BankCard {
            get {
                return ResourceManager.GetString("BankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中英混合 的本地化字符串。
        /// </summary>
        public static string CH_ENMixture {
            get {
                return ResourceManager.GetString("CH-ENMixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright (C) 2020-2024 鹰眼OCR 的本地化字符串。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别后复制 的本地化字符串。
        /// </summary>
        public static string CopyToClipboardAfterOCR {
            get {
                return ResourceManager.GetString("CopyToClipboardAfterOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除本地数据 的本地化字符串。
        /// </summary>
        public static string DeleteLocalData {
            get {
                return ResourceManager.GetString("DeleteLocalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英文 的本地化字符串。
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定截图 的本地化字符串。
        /// </summary>
        public static string FixedScreenshot {
            get {
                return ResourceManager.GetString("FixedScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定截图区域 的本地化字符串。
        /// </summary>
        public static string FixedScreenshotArea {
            get {
                return ResourceManager.GetString("FixedScreenshotArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定截图热键 的本地化字符串。
        /// </summary>
        public static string FixedScreenshotHotkey {
            get {
                return ResourceManager.GetString("FixedScreenshotHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公式 的本地化字符串。
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 法语 的本地化字符串。
        /// </summary>
        public static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用文字 的本地化字符串。
        /// </summary>
        public static string GeneralText {
            get {
                return ResourceManager.GetString("GeneralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 德语 的本地化字符串。
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手写文字 的本地化字符串。
        /// </summary>
        public static string HandwrittenText {
            get {
                return ResourceManager.GetString("HandwrittenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通用高精度 的本地化字符串。
        /// </summary>
        public static string High_precisionText {
            get {
                return ResourceManager.GetString("High-precisionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 热键 的本地化字符串。
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份证 的本地化字符串。
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        public static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介绍： 的本地化字符串。
        /// </summary>
        public static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鹰眼OCR是基于.NET9.0的文字识别程序。 的本地化字符串。
        /// </summary>
        public static string Introduction_Line_1 {
            get {
                return ResourceManager.GetString("Introduction_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢您的使用！ 的本地化字符串。
        /// </summary>
        public static string Introduction_Line_2 {
            get {
                return ResourceManager.GetString("Introduction_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意大利语 的本地化字符串。
        /// </summary>
        public static string Italian {
            get {
                return ResourceManager.GetString("Italian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日语 的本地化字符串。
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度 ApiKey 的本地化字符串。
        /// </summary>
        public static string KeyTitle {
            get {
                return ResourceManager.GetString("KeyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 韩语 的本地化字符串。
        /// </summary>
        public static string Korean {
            get {
                return ResourceManager.GetString("Korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫秒 的本地化字符串。
        /// </summary>
        public static string Millisecond {
            get {
                return ResourceManager.GetString("Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国徽面 的本地化字符串。
        /// </summary>
        public static string NationalEmblemSurface {
            get {
                return ResourceManager.GetString("NationalEmblemSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注： 的本地化字符串。
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本程序图片素材均来源于网络，仅供学习之用， 的本地化字符串。
        /// </summary>
        public static string Note_Line_1 {
            get {
                return ResourceManager.GetString("Note_Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢原作者的分享！ 的本地化字符串。
        /// </summary>
        public static string Note_Line_2 {
            get {
                return ResourceManager.GetString("Note_Line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置 的本地化字符串。
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数字 的本地化字符串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PDF识别每页延迟 的本地化字符串。
        /// </summary>
        public static string PDF_OCR_Delay {
            get {
                return ResourceManager.GetString("PDF_OCR_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拍照热键 的本地化字符串。
        /// </summary>
        public static string PhotographHotkey {
            get {
                return ResourceManager.GetString("PhotographHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 照片面 的本地化字符串。
        /// </summary>
        public static string PhotoSurface {
            get {
                return ResourceManager.GetString("PhotoSurface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 葡萄牙语 的本地化字符串。
        /// </summary>
        public static string Portuguese {
            get {
                return ResourceManager.GetString("Portuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码 的本地化字符串。
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录音热键 的本地化字符串。
        /// </summary>
        public static string RecordingHotkey {
            get {
                return ResourceManager.GetString("RecordingHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俄语 的本地化字符串。
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存拍照 的本地化字符串。
        /// </summary>
        public static string SavePhoto {
            get {
                return ResourceManager.GetString("SavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存录音 的本地化字符串。
        /// </summary>
        public static string SaveRecording {
            get {
                return ResourceManager.GetString("SaveRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存截图到剪切板 的本地化字符串。
        /// </summary>
        public static string SaveScreenshotToClipboard {
            get {
                return ResourceManager.GetString("SaveScreenshotToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存截图到本地 的本地化字符串。
        /// </summary>
        public static string SaveScreenshotToLocal {
            get {
                return ResourceManager.GetString("SaveScreenshotToLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存语音合成 的本地化字符串。
        /// </summary>
        public static string SaveSpeechSynthesis {
            get {
                return ResourceManager.GetString("SaveSpeechSynthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截图热键 的本地化字符串。
        /// </summary>
        public static string ScreenshotHotkey {
            get {
                return ResourceManager.GetString("ScreenshotHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置固定截图坐标 的本地化字符串。
        /// </summary>
        public static string SetCoordinates {
            get {
                return ResourceManager.GetString("SetCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 西班牙语 的本地化字符串。
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发音人 的本地化字符串。
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语速 的本地化字符串。
        /// </summary>
        public static string SpeechRate {
            get {
                return ResourceManager.GetString("SpeechRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表格 的本地化字符串。
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别后翻译 的本地化字符串。
        /// </summary>
        public static string TranslateAtferOCR {
            get {
                return ResourceManager.GetString("TranslateAtferOCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译 的本地化字符串。
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新日志 的本地化字符串。
        /// </summary>
        public static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本信息 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看本地数据 的本地化字符串。
        /// </summary>
        public static string ViewLocalData {
            get {
                return ResourceManager.GetString("ViewLocalData", resourceCulture);
            }
        }
    }
}
