<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	<GenerateAssemblyInfo>True</GenerateAssemblyInfo>
	<OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\鹰眼OCR_Common\鹰眼OCR_Common.csproj" />
  </ItemGroup>

</Project>
